CREATE DATABASE demo_provider CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE demo_provider;

CREATE TABLE tbl_user (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  CREATE_TIME datetime NOT NULL,
  VERSION bigint(20) NOT NULL DEFAULT '0',
  USER_NO char(30) NOT NULL,
  USER_NAME varchar(80) NOT NULL,
  REAL_NAME varchar(100) NOT NULL,
  GENDER tinyint(1) NOT NULL,
  AGE smallint(6) NOT NULL,
  ANNUAL_INCOME decimal(20,2) NOT NULL DEFAULT '0.00',
  IS_PROGRAMMER tinyint(1) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_USERNAME (USER_NAME),
  UNIQUE KEY UK_USERNO (USER_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE tbl_user_ext (
  USER_NO char(30) NOT NULL COMMENT '用户编号(主键)',
  VERSION bigint(20) NOT NULL DEFAULT '0',
  CREATE_TIME datetime NOT NULL,
  ADDRESS varchar(200) DEFAULT NULL COMMENT '地址',
  HEIGHT smallint(6) DEFAULT NULL COMMENT '身高(cm)',
  WEIGHT decimal(5,2) DEFAULT NULL COMMENT '体重(kg)',
  PRIMARY KEY (USER_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户拓展表';